.gitignore, Cargo.lock, Cargo.toml, intermediate-proof-storage/Cargo.toml, intermediate-proof-storage/src/lib.rs, prover/src/common/mod.rs, prover/src/common/targets.rs, prover/src/latest_validator_set.rs, prover/src/lib.rs, relayer/Cargo.toml, relayer/src/main.rs
=> Generic storage of intermediate proofs

Cargo.lock, circuits/plonky2_blake2b256/src/circuit.rs, circuits/plonky2_blake2b256/src/utils.rs, prover/Cargo.toml, prover/src/common/mod.rs, prover/src/common/targets.rs, prover/src/storage_proof/generic_hasher.rs, prover/src/storage_proof/mod.rs, prover/src/storage_proof/node_parser/branch_parser/child_node_array_parser/mod.rs, prover/src/storage_proof/node_parser/branch_parser/mod.rs, prover/src/storage_proof/node_parser/mod.rs
=> Generic blake2 hasher

prover/Cargo.toml, prover/src/common/mod.rs, prover/src/storage_proof/branch_node_chain.rs, prover/src/storage_proof/generic_hasher.rs, prover/src/storage_proof/hashed_branch_parser.rs, prover/src/storage_proof/hashed_leaf_parser.rs, prover/src/storage_proof/mod.rs, prover/src/storage_proof/node_parser/branch_parser/mod.rs, prover/src/storage_proof/node_parser/mod.rs
=> Implement storage trie circuit

gnark-wrapper/main.go, prover/src/common/targets/mod.rs, prover/src/final_proof/message_sent.rs, prover/src/lib.rs
=> Compress public inputs in gnark-wrapper

prover/src/common/targets/array.rs, prover/src/common/targets/byte.rs, prover/src/common/targets/mod.rs, prover/src/common/targets/target.rs, prover/src/final_proof/message_sent.rs, prover/src/latest_validator_set/mod.rs, prover/src/latest_validator_set/next_validator_set.rs, prover/src/lib.rs, relayer/src/main.rs
=> Integrate with `pallet-gear-bridges`

Cargo.lock, gnark-wrapper/main.go, relayer/src/prover_interface.rs
=> refactor(gnark-wrapper): Lazy gnark circuit compilation

ethereum/client/src/abi.rs, ethereum/client/src/error.rs, ethereum/client/src/lib.rs, gear-rpc-client/src/dto.rs, gear-rpc-client/src/lib.rs, relayer/src/main.rs, relayer/src/prover_interface.rs, relayer/src/relay_merkle_roots.rs, relayer/src/relay_messages.rs
=> refactor(relayer): Wait for ethereum block finality

Cargo.lock, Cargo.toml, relayer/Cargo.toml, relayer/src/main.rs, relayer/src/message_relayer/event_listener.rs, relayer/src/message_relayer/merkle_root_listener.rs, relayer/src/message_relayer/message_processor.rs, relayer/src/message_relayer/mod.rs, relayer/src/metrics.rs, relayer/src/prover_interface.rs, relayer/src/relay_merkle_roots.rs, relayer/src/relay_messages.rs
=> feat(relayer): Add prometheus metrics

.gitignore, ethereum/client/src/abi.rs, ethereum/client/src/convert.rs, ethereum/client/src/lib.rs, ethereum/src/MessageQueue.sol, ethereum/src/interfaces/IMessageQueue.sol, ethereum/test/MessageQueue.t.sol, ethereum/test/TestHelper.t.sol, ethereum/test/Treasury.t.sol, ethereum/test/Verifier.t.sol, relayer/src/message_relayer/message_processor.rs, relayer/src/message_relayer/mod.rs
VaraMessage : Nonce type changed from uint256 to  bytes32
Tests updated:  Verifier  replaced with VerifierMock, hashes updated.
=> feat(ethereum contracts): Change nonce type and update tests

Cargo.lock, Cargo.toml, relayer/Cargo.toml, relayer/src/main.rs, relayer/src/message_relayer/event_listener.rs, relayer/src/message_relayer/merkle_root_listener.rs, relayer/src/message_relayer/message_processor.rs, relayer/src/message_relayer/mod.rs, relayer/src/proof_storage/gear.rs, relayer/src/prover_interface.rs, relayer/src/relay_merkle_roots.rs, utils-prometheus/Cargo.toml, utils-prometheus/src/lib.rs
=> chore: Introduce new module utils-prometheus

Cargo.lock, Cargo.toml, ethereum-common/Cargo.toml, ethereum-common/src/beacon/tests.rs, ethereum-common/src/keccak_hasher.rs, ethereum-common/src/lib.rs, ethereum-common/src/memory_db.rs, ethereum-common/src/patricia_trie.rs, ethereum-common/src/rlp_node_codec.rs, ethereum-common/src/utils.rs
=> feat: Add merkle patricia trie to ethereum-common

ethereum-common/src/base_types/fixed_array.rs, ethereum-common/src/base_types/list.rs, ethereum-common/src/beacon/block.rs, ethereum-common/src/beacon/block_body.rs, ethereum-common/src/beacon/block_header.rs, ethereum-common/src/beacon/common.rs, ethereum-common/src/beacon/execution_payload.rs, ethereum-common/src/beacon/light.rs, ethereum-common/src/beacon/mod.rs, gear-programs/checkpoint-light-client/io/src/lib.rs
- impl From for beacon BlockHeader
- fix Decode implementation for List
- remove unnecessary trait bounds
@gear-tech/dev
=> refactor: Add light versions of some entities

Cargo.lock, ethereum/src/libraries/PlonkVerifier.sol, relayer/src/message_relayer/event_listener.rs, relayer/src/message_relayer/merkle_root_listener.rs, relayer/src/relay_merkle_roots.rs
=> bugfix(relayers): Fix `async` blocks in relayers

.dockerignore, Dockerfile
=> feat: Containerize relayers

.github/workflows/ci.yml, circuits/plonky2_ed25519/src/gadgets/eddsa.rs, ethereum/client/src/tests.rs, gear-programs/vft-gateway/src/wasm/tests/vft_gateway.rs, relayer/src/ethereum_checkpoints/tests/mod.rs
=> chore: Make CI run tests

gear-programs/vft-gateway/src/services/mod.rs, gear-programs/vft-gateway/src/wasm/tests/utils.rs, gear-programs/vft-gateway/src/wasm/tests/vft_gateway.rs, gear-programs/vft-gateway/src/wasm/vft-gateway.idl
=> refactor(vft-gateway): Set eth_client to admin by default and add update_eth_client method

gear-programs/erc20-relay/app/src/lib.rs, gear-programs/erc20-relay/app/src/service.rs, gear-programs/erc20-relay/app/tests/gclient.rs
=> refactor(erc20-relay): Add various getters

Cargo.lock, ethereum-common/src/base_types/byte_list.rs, ethereum-common/src/base_types/bytes_fixed.rs, ethereum-common/src/base_types/fixed_array.rs, ethereum-common/src/beacon/block.rs, ethereum-common/src/beacon/block_body.rs, ethereum-common/src/beacon/block_header.rs, ethereum-common/src/beacon/common.rs, ethereum-common/src/beacon/execution_payload.rs, ethereum-common/src/beacon/light.rs, ethereum-common/src/lib.rs, gear-programs/erc20-relay/client/Cargo.toml, gear-programs/erc20-relay/client/build.rs, relayer/src/erc20/mod.rs
=> refactor(erc20-relay): Set external types

gear-programs/erc20-relay/app/src/lib.rs, gear-programs/erc20-relay/app/src/service.rs, gear-programs/erc20-relay/app/tests/gclient.rs
=> refactor(erc20-relay): Extend `Relayed` event

relayer/src/main.rs
=> refactor(relayer): Use formatted timed log-builder

Cargo.lock, Cargo.toml, gear-programs/bridging-payment-vara-supply/app/src/services/mod.rs, gear-programs/bridging-payment-vara-supply/tests/gtest.rs, gear-programs/bridging-payment/app/Cargo.toml, gear-programs/bridging-payment/app/src/services/mod.rs, gear-programs/bridging-payment/tests/gtest.rs, gear-programs/checkpoint-light-client/Cargo.toml, gear-programs/checkpoint-light-client/build.rs, gear-programs/erc20-relay/app/Cargo.toml, gear-programs/erc20-relay/app/tests/gclient.rs, gear-programs/proof-storage/Cargo.toml, gear-programs/vft-gateway/app/Cargo.toml, gear-programs/vft-gateway/tests/gtest.rs, gear-programs/vft-treasury/app/Cargo.toml, gear-programs/vft-treasury/tests/gtest.rs, gear-rpc-client/src/lib.rs
=> chore: Update to gear v1.6.2

gear-programs/vft-gateway/app/src/services/mod.rs, gear-programs/vft-gateway/tests/gtest.rs
use receiver_contract_address instead
@gear-tech/dev
=> refactor(vft-gateway): Remove unnecessary eth_contract_address

gear-rpc-client/src/lib.rs, relayer/src/ethereum_checkpoints/mod.rs, relayer/src/main.rs, relayer/src/proof_storage/gear.rs, tools/genesis-config/src/main.rs
=> feat(relayer): Introduce VaraArgs with retries count

frontend/src/utils.ts
=> fix(frontend): validate ss58 address length

.github/workflows/ci.yml
=> chore(ci): Revert cargo build fix

.github/workflows/ci.yml
=> chore(ci): Disable cache

relayer/src/message_relayer/common/ethereum/message_sender/era.rs
=> fix(relayer): Don't spam messages to log in gear->eth relayer

indexer/Dockerfile, indexer/src/gear/config.ts, indexer/src/gear/main.ts, indexer/src/gear/processor.ts
=> feat(indexer): update indexer to use historical proxy instead of erc20-relay

relayer/src/message_relayer/common/gear/message_sender/mod.rs
=> fix(relayer): Resend message in eth->gear relayer if it's failed

indexer/db/migrations/1733751857295-Data.js, indexer/package.json, indexer/schema.graphql, indexer/src/common/tempState.ts, indexer/src/eth/main.ts, indexer/src/gear/main.ts, indexer/src/model/generated/completedTransfer.model.ts, indexer/src/model/generated/transfer.model.ts
=> feat(indexer): store time when transfer is completed

Cargo.lock, gear-programs/historical-proxy/app/tests/gclient.rs
=> chore: Commit regenerated Cargo.lock

frontend/src/features/swap/components/submit-progress-bar/submit-progress-bar.tsx, frontend/src/features/swap/components/swap-form/swap-form.tsx, frontend/src/features/swap/errors.ts, frontend/src/features/swap/hooks/eth/use-handle-eth-submit.ts, frontend/src/features/swap/hooks/use-swap-form.ts, frontend/src/features/swap/hooks/vara/use-handle-vara-submit.ts, frontend/src/features/swap/utils.ts
=> fix(frontend): consider existential deposit during balance validation

api/gear/ethereum_event_client.idl, ethereum-common/src/base_types/byte_list.rs, ethereum-common/src/base_types/bytes_fixed.rs, ethereum-common/src/base_types/fixed_array.rs, ethereum-common/src/base_types/list.rs, ethereum-common/src/base_types/mod.rs, ethereum-common/src/beacon/block.rs, ethereum-common/src/beacon/block_body.rs, ethereum-common/src/beacon/block_header.rs, ethereum-common/src/beacon/common.rs, ethereum-common/src/beacon/execution_payload.rs, ethereum-common/src/beacon/light.rs, ethereum-common/src/lib.rs, ethereum-common/src/merkle.rs, ethereum-common/src/utils.rs
=> refactor(ethereum-common): Add documentation comments

gear-programs/vft-manager/app/src/services/request_bridging/mod.rs
=> fix(vft-manager): Fix possible funds lock

Cargo.lock, Cargo.toml, api/gear/vft_manager.idl, gear-programs/vft-manager/app/src/services/error.rs, gear-programs/vft-manager/app/src/services/mod.rs, gear-programs/vft-manager/tests/gtest.rs
=> feat(vft-manager): Add pause functionality

relayer/src/cli/common.rs, relayer/src/cli/mod.rs, relayer/src/ethereum_checkpoints/mod.rs, relayer/src/ethereum_checkpoints/replay_back.rs, relayer/src/main.rs
=> feat(relayer): Add size batch and multiplier arguments to CLI instead of constants

ethereum-common/src/network.rs, tools/deploy-checkpoints/src/main.rs
https://github.com/eth-clients/hoodi
@gear-tech/dev
=> feat(ethereum-common, deploy-checkpoints): Add support of the Hoodi testnet

Cargo.lock, tools/governance/Cargo.toml, tools/governance/src/main.rs
=> feat(tooling): Extend governance tooling

ethereum-common/src/network.rs
=> feat(ethereum-common): Add Electra fork activation time for the Mainnet

api/gear/vft_manager.idl, gear-programs/vft-manager/app/src/services/mod.rs, gear-programs/vft-manager/app/src/services/request_bridging/bridge_builtin_operations.rs, gear-programs/vft-manager/app/tests/gclient.rs, gear-programs/vft-manager/tests/gtest.rs
=> feat(vft-manager): Add fees for incoming bridge requests and pay fee to the bridge-builtin

api/gear/vft_manager.idl, gear-programs/vft-manager/app/src/services/mod.rs, gear-programs/vft-manager/app/src/services/token_mapping.rs
=> refactor(vft-manager): Add supply type to the events

api/gear/eth_events_deneb.idl, api/gear/eth_events_electra.idl, api/gear/historical_proxy.idl, gear-programs/eth-events-common/src/lib.rs, gear-programs/eth-events-deneb/app/src/lib.rs, gear-programs/eth-events-electra/app/src/lib.rs, gear-programs/historical-proxy/app/src/service.rs, gear-programs/historical-proxy/app/tests/gclient.rs
=> refactor(historical proxy): Add method to update admin 

frontend/src/features/swap/components/submit-progress-bar/submit-progress-bar.tsx, frontend/src/features/swap/components/swap-form/swap-form.tsx, frontend/src/features/swap/hooks/vara/use-handle-vara-submit.ts, frontend/src/features/swap/hooks/vara/use-sign-and-send.ts, frontend/src/features/token-price/components/token-price/token-price.tsx
=> feat(frontend): Send Vara transactions in batch

relayer/src/message_relayer/common/gear/checkpoints_extractor.rs
=> fix(relayer): Skip reply route before decoding the reply in checkpoints extractor

.github/workflows/ci.yml
=> chore(ci): update gear node from 1.6.2 to 1.7.1

tools/deploy-to-gear/src/main.rs
=> feat(tools): use random salt or one passed through CLI

.github/workflows/ci.yml, gear-programs/checkpoint-light-client/app/tests/gclient.rs, gear-programs/historical-proxy/app/tests/gclient.rs, gear-programs/vft-manager/app/tests/gclient.rs
=> chore(ci): update from node 1.7.1 to 1.8.0

relayer/src/main.rs, relayer/src/message_relayer/gear_to_eth/manual.rs
=> fix(relayer): Decode U256 from hex string

relayer/src/message_relayer/common/ethereum/deposit_event_extractor.rs, relayer/src/message_relayer/common/ethereum/merkle_root_extractor.rs, relayer/src/message_relayer/common/ethereum/message_paid_event_extractor.rs, relayer/src/message_relayer/common/ethereum/message_sender/mod.rs, relayer/src/message_relayer/common/gear/checkpoints_extractor.rs, relayer/src/message_relayer/common/gear/message_paid_event_extractor.rs, relayer/src/message_relayer/common/gear/message_queued_event_extractor.rs, relayer/src/message_relayer/common/gear/message_sender/mod.rs, relayer/src/message_relayer/common/paid_messages_filter.rs, relayer/src/message_relayer/eth_to_gear/api_provider.rs
=> fix(relayer): Use asynchronous recv method instead of try_recv

relayer/src/message_relayer/eth_to_gear/api_provider.rs
=> fix(relayer): Set the current api provider session in the response

relayer/src/kill_switch.rs, relayer/src/kill_switch/block_finality_archiver.rs, relayer/src/main.rs, relayer/src/message_relayer/common/ethereum/merkle_root_extractor.rs, relayer/src/message_relayer/common/ethereum/message_sender/mod.rs, relayer/src/message_relayer/common/gear/message_paid_event_extractor.rs, relayer/src/message_relayer/common/gear/message_queued_event_extractor.rs, relayer/src/message_relayer/gear_to_eth/all_token_transfers.rs, relayer/src/message_relayer/gear_to_eth/manual.rs, relayer/src/message_relayer/gear_to_eth/paid_token_transfers.rs, relayer/src/relay_merkle_roots.rs
=> refactor(relayer): use ApiProvider to acquire GearApi instances

relayer/src/cli/mod.rs, relayer/src/main.rs, relayer/src/message_relayer/common/gear/message_sender/mod.rs, relayer/src/message_relayer/eth_to_gear/manual.rs
- send message to the channel before the loop
- decode and log replies from vft-manager
- make more descriptive error if it is unable to get balance
@gear-tech/dev
=> fix(relayer): Fix manual relayer for eth-> gear direction

relayer/src/message_relayer/common/ethereum/mod.rs
Increase attempt count to find the corresponding beacon block for eth to gear direction
@gear-tech/dev
=> fix(relayer): Increase attempt count

relayer/src/message_relayer/eth_to_gear/api_provider.rs
=> fix(relayer): Use the current session in ApiProviderConnection::reconnect

.envrc, .gitignore, flake.lock, flake.nix
=> feat(tooling): add nix dev shell with flake.nix

frontend/src/components/formatted-balance/fortmatted-balance.tsx, frontend/src/features/swap/components/amount-input/amount-input.tsx, frontend/src/features/swap/components/swap-form/swap-form.tsx, frontend/src/features/token-price/components/token-price/token-price.tsx
=> feat(frontend): Remove SI units from formatted balances

relayer/src/cli/mod.rs, relayer/src/main.rs, relayer/src/relay_merkle_roots.rs
=> feat(relayer): Add posibility to relay merkle proofs from the specified set_id

frontend/src/components/address/address.tsx, frontend/src/features/history/components/transaction-card/transaction-card.module.scss, frontend/src/features/history/components/transaction-card/transaction-card.tsx, frontend/src/features/history/components/transaction-modal/transaction-modal.module.scss, frontend/src/features/history/components/transaction-modal/transaction-modal.tsx, frontend/src/features/swap/components/token/token.module.scss, frontend/src/features/wallet/components/wallet/wallet.module.scss, frontend/src/features/wallet/components/wallet/wallet.tsx, frontend/src/utils/index.ts
=> feat(frontend): Display end of truncated addresses

indexer/db/migrations/1747321174093-Data.js, indexer/package.json, indexer/schema.graphql, indexer/src/common/tempState.ts, indexer/src/eth/main.ts, indexer/src/gear/main.ts, indexer/src/gear/processor.ts, indexer/src/model/generated/_status.ts, indexer/src/model/generated/transfer.model.ts
```graphql
enum Status {
Pending
InProgress
Completed
Failed
}
```
=>
```graphql
enum Status {
AwaitingPayment
Bridging
Completed
Failed
}
```
=> feat(indexer): update bridging statuses

.github/workflows/build-and-publish-relayer.yml, Dockerfile
=> fix: Fix docker warnings

.github/workflows/ci.yml
=> refactor(ci): merge check-api-files into build step

relayer/src/message_relayer/common/gear/block_listener.rs
=> refactor(relayer): Don't change current block in listener on gearApi reconnect

relayer/src/message_relayer/eth_to_gear/api_provider.rs
=> refactor(relayer): Attempt 10 reconnects in ApiProvider

gear-programs/checkpoint-light-client/app/src/services/mod.rs, gear-programs/checkpoint-light-client/app/src/services/replay_back.rs, gear-programs/checkpoint-light-client/app/src/services/sync_update/mod.rs, tests/src/checkpoint_light_client/mod.rs
=> refactor(checkpoint-light-client): emit event on new checkpoint

Cargo.lock, Cargo.toml, gear-common/Cargo.toml, gear-common/src/lib.rs, tests/Cargo.toml, tests/src/lib.rs, tests/src/vft.rs, tools/deploy-to-gear/Cargo.toml, tools/deploy-to-gear/src/main.rs
=> feat(deploy-to-gear): Add command to migrate VFT balances

api/gear/vft_manager.idl, gear-programs/vft-manager/app/src/services/mod.rs
Resolves #448 
-
@gear-tech/dev
=> refactor(vft-manager): Add new events

relayer/src/message_relayer/eth_to_gear/message_sender.rs, relayer/src/message_relayer/eth_to_gear/proof_composer.rs, relayer/src/message_relayer/eth_to_gear/tx_manager.rs
=> fix(relayer): Fix bug when TransactionManager did not terminate gracefully

api/gear/vft_manager.idl, gear-programs/vft-manager/app/src/services/mod.rs, gear-programs/vft-manager/app/src/services/request_bridging/mod.rs, gear-programs/vft-manager/app/src/services/submit_receipt/mod.rs, gear-programs/vft-manager/tests/gtest.rs, tests/src/vft_manager/mod.rs
=> refactor(vft-manager): Init in paused state with erc20_manager_address set to None

Cargo.lock, Cargo.toml, api/gear/vft_manager.idl, gear-common/Cargo.toml, gear-common/src/lib.rs, gear-programs/vft-manager/app/src/services/mod.rs, gear-programs/vft-manager/app/src/services/submit_receipt/mod.rs, tests/src/vft_manager/mod.rs, tools/vft-manager-tool/Cargo.toml, tools/vft-manager-tool/src/main.rs
supports deployment of the new VftManger and transfer of all old settings. Additional command `migrate-transactions`.
@gear-tech/dev
=> feat(tools): vft-manager-tool

relayer/src/message_relayer/eth_to_gear/storage.rs, relayer/src/message_relayer/eth_to_gear/tx_manager.rs
=> fix(relayer): remove tx from block storage once in tx manager

relayer/src/main.rs, relayer/src/message_relayer/common/ethereum/deposit_event_extractor.rs, relayer/src/message_relayer/common/ethereum/message_paid_event_extractor.rs, relayer/src/message_relayer/eth_to_gear/proof_composer.rs
=> fix(relayer): remove unecessary infinite loop preventing restarts

ethereum/client/src/lib.rs, relayer/src/message_relayer/common/gear/message_paid_event_extractor.rs, relayer/src/message_relayer/common/gear/message_queued_event_extractor.rs
make logs in gear event extractors less noisy
@gear-tech/dev
=> refactor(relayer): Increase max_priority_fee_per_gas/max_fee_per_gas for gear-eth

relayer/src/message_relayer/common/gear/message_queued_event_extractor.rs
=> fix(relayer): exit MessageQueueEventExtractor if channel is closed

relayer/src/main.rs, relayer/src/merkle_roots/authority_set_sync.rs, relayer/src/merkle_roots/prover.rs
=> fix(relayer): spawn relayer with at least 4 blocking threads, revert to spawn_blocking

ethereum/client/src/abi.rs, ethereum/client/src/error.rs, ethereum/client/src/lib.rs
=> feat(relayer): Decode Ethereum contract errors

Cargo.lock, api/gear/vft_vara.idl, gear-programs/vft-vara/app/src/lib.rs, tests/src/vft_manager/gtest.rs, tests/src/vft_manager/mod.rs, tools/deploy-to-gear/Cargo.toml, tools/deploy-to-gear/src/main.rs
=> refactor(vft, vft-vara): Adjust tokens names & etc

gear-rpc-client/src/lib.rs, relayer/src/main.rs
=> fix: return AccountId32 directly

prover/src/common/mod.rs
=> feat(circuits): Implement Gate/Generator serialization with U32AddMany* and U32Arithmetic*

.github/workflows/ci.yml, prover/src/common/generic_blake2.rs, prover/src/common/mod.rs, prover/src/lib.rs, prover/src/serialization.rs
=> feat(circuits): Introduce ReadAdapter and use it in VariativeBlake2

gear-rpc-client/src/lib.rs
=> fix(relayer): fix gear-rpc-client error
