gear-tech/gear-bridges

prover/src/block_finality/mod.rs, prover/src/block_finality/validator_signs_chain/indexed_validator_sign.rs, prover/src/block_finality/validator_signs_chain/mod.rs, prover/src/block_finality/validator_signs_chain/single_validator_sign.rs, prover/src/common/generic_blake2.rs, prover/src/common/mod.rs, prover/src/common/targets/byte.rs, prover/src/latest_validator_set/mod.rs, prover/src/lib.rs, prover/src/storage_inclusion/storage_trie_proof/branch_node_chain.rs, prover/src/storage_inclusion/storage_trie_proof/node_parser/branch_parser/child_node_array_parser/mod.rs, relayer/src/main.rs
Circuit build time relates to proving time as ~ 2/3. So caching circuit for `ed25519` will allow to decrease overall proving time by 30-40% on mainnet as validator sign proofs take ~90% of overall proving time
=> Cache `SingleValidatorSign` circuit

gear-programs/checkpoint-light-client/io/src/lib.rs, gear-programs/checkpoint-light-client/io/src/meta.rs, gear-programs/checkpoint-light-client/io/src/sync_update.rs, gear-programs/checkpoint-light-client/src/wasm/mod.rs, gear-programs/checkpoint-light-client/src/wasm/sync_update.rs, gear-programs/checkpoint-light-client/src/wasm/utils.rs, relayer/src/ethereum_checkpoints/mod.rs
=> refactor: Add GetState request

Cargo.lock, gear-programs/checkpoint-light-client/Cargo.toml, relayer/src/ethereum_checkpoints/mod.rs, relayer/src/ethereum_checkpoints/replay_back.rs, relayer/src/ethereum_checkpoints/sync_update.rs
Resolves #97 
- continue execution after blocks have been replayed back
- create gear events listener on demand to avoid errors spam on pruning nodes
- 
@gear-tech/dev
=> refactor: Change replay back mechanism

gear-programs/vft-gateway/src/services/error.rs, gear-programs/vft-gateway/src/services/mod.rs, gear-programs/vft-gateway/src/wasm/tests/utils.rs, gear-programs/vft-gateway/src/wasm/tests/vft_gateway.rs, gear-programs/vft-gateway/src/wasm/vft-gateway.idl
suggested in https://github.com/gear-tech/gear-bridges/pull/116#discussion_r1766881102
@gear-tech/dev
=> refactor(vft-gateway): Remove Vara address from MintTokens service/message

gear-programs/checkpoint-light-client/src/wasm/mod.rs, gear-programs/checkpoint-light-client/src/wasm/state.rs, gear-programs/checkpoint-light-client/src/wasm/utils.rs
=> refactor(checkpoints): Store slot directly with a checkpoint

Cargo.lock, ethereum-common/Cargo.toml, ethereum-common/src/lib.rs, ethereum-common/src/utils.rs, relayer/src/erc20/mod.rs, relayer/src/ethereum_checkpoints/mod.rs, relayer/src/ethereum_checkpoints/tests/mod.rs, relayer/src/ethereum_checkpoints/utils/mod.rs
Resolves #159 
- `map_receipt_envelope` func
- introduce `generate_proof` func
- move `Beacon*` structs
@gear-tech/dev
=> refactor: Move some entities to ethereum-common

.gitignore, GenesisConfig.toml
CD Requires that `GenesisConfig.toml` is present in repo, but it was in `.gitignore` previously
=> fix(CD): Add `GenesisConfig.toml` to repo

gear-programs/bridging-payment/tests/gtest.rs, gear-programs/vft-gateway/app/src/services/mod.rs, gear-programs/vft-gateway/src/wasm/vft-gateway.idl, gear-programs/vft-gateway/tests/gtest.rs
These events will be used by indexer
`vft-treasury` is left unchanged due to #163
=> feat(gear-programs): Emit events in `vft-gateway`

ethereum/src/ERC20Gateway.sol, ethereum/src/ERC20Treasury.sol, ethereum/src/MessageQueue.sol, ethereum/src/ProxyContract.sol, ethereum/src/ProxyUpdater.sol, ethereum/src/interfaces/IERC20Gateway.sol, ethereum/src/interfaces/IERC20Treasury.sol, ethereum/src/interfaces/IMessageQueue.sol, ethereum/test/ProxyUpdater.t.sol, ethereum/test/Treasury.t.sol
Resolves #153 
Also resolves #72
=> feat(ethereum contracts): Introduce governance-driven `ProxyUpdater`

Cargo.lock, Cargo.toml
Removes pinned branch for the `extended_vft_wasm` dependency.
=> chore: remove pinned branch for the `extended_vft_wasm` dependency

relayer/src/cli/common.rs, relayer/src/cli/mod.rs, relayer/src/ethereum_checkpoints/mod.rs, relayer/src/hex_utils.rs, relayer/src/main.rs, relayer/src/message_relayer/common/ethereum/deposit_event_extractor.rs, relayer/src/message_relayer/common/gear/message_sender/mod.rs, relayer/src/message_relayer/eth_to_gear/all_token_transfers.rs, relayer/src/message_relayer/eth_to_gear/manual.rs, relayer/src/message_relayer/eth_to_gear/mod.rs, relayer/src/message_relayer/eth_to_gear/paid_token_transfers.rs, relayer/src/message_relayer/gear_to_eth/manual.rs, relayer/src/message_relayer/gear_to_eth/mod.rs
=> feat(relayer): Introduce manual relayers

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/formatted-balance/fortmatted-balance.module.scss, frontend/src/components/formatted-balance/fortmatted-balance.tsx, frontend/src/components/formatted-balance/index.ts, frontend/src/components/index.ts, frontend/src/components/tooltip/tooltip.module.scss, frontend/src/components/tooltip/tooltip.tsx, frontend/src/features/history/components/transaction-modal/transaction-modal.tsx, frontend/src/features/history/components/transaction-pair/transaction-pair.tsx, frontend/src/features/swap/components/account-balance/account-balance.tsx, frontend/src/features/swap/components/balance/balance.module.scss, frontend/src/features/swap/components/balance/balance.tsx, frontend/src/features/swap/components/ft-allowance-tip/ft-allowance-tip.tsx, frontend/src/features/swap/components/swap-form/swap-form.tsx, frontend/src/features/swap/hooks/eth/use-eth-ft-balance.ts, frontend/src/features/swap/hooks/use-swap-form.ts, frontend/src/features/swap/types/hooks.ts, frontend/src/features/swap/utils.ts, frontend/src/features/token-tracker/components/card/balance-card.tsx, frontend/src/features/token-tracker/components/token-tracker-modal/token-tracker-modal.tsx, frontend/src/features/token-tracker/components/token-tracker/token-tracker.tsx, frontend/src/hooks/use-eth-account-balance.ts, frontend/src/hooks/use-vara-account-balance.ts, frontend/src/hooks/use-vara-ft-balance.ts
=> feat(frontend): add SI balance formatting

Dockerfile
From rustup 1.28.0 it now [requires](https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html) "override" toolchain to be explicitly installed via `rustup toolchain install` before running `cargo build`
=> fix(cd): Explicitly install rust toolchain

api/gear/vft_manager.idl, gear-programs/vft-manager/Cargo.toml, gear-programs/vft-manager/app/Cargo.toml, gear-programs/vft-manager/app/src/lib.rs, gear-programs/vft-manager/app/src/services/mod.rs, gear-programs/vft-manager/app/src/services/request_bridging/mod.rs, gear-programs/vft-manager/app/src/services/request_bridging/msg_tracker.rs, gear-programs/vft-manager/app/src/services/submit_receipt/mod.rs, gear-programs/vft-manager/app/tests/gclient.rs
The first part of the upgrade-able feature. Adds new getter for the processed Ethereum-transactions and refactors the msg_tracker state getter.
@gear-tech/dev
=> refactor(vft-manager): Add new getters

Cargo.lock, Cargo.toml, ethereum/client/src/lib.rs, ethereum_beacon_client/src/lib.rs, relayer/Cargo.toml, relayer/src/main.rs, relayer/src/message_relayer/common/ethereum/block_listener.rs, relayer/src/message_relayer/common/ethereum/deposit_event_extractor.rs, relayer/src/message_relayer/common/ethereum/merkle_root_extractor.rs, relayer/src/message_relayer/common/ethereum/message_paid_event_extractor.rs, relayer/src/message_relayer/common/ethereum/message_sender/mod.rs, relayer/src/message_relayer/common/gear/block_listener.rs, relayer/src/message_relayer/common/gear/checkpoints_extractor.rs, relayer/src/message_relayer/common/gear/message_paid_event_extractor.rs, relayer/src/message_relayer/common/gear/message_queued_event_extractor.rs, relayer/src/message_relayer/common/gear/message_sender/mod.rs, relayer/src/message_relayer/common/paid_messages_filter.rs, relayer/src/message_relayer/eth_to_gear/all_token_transfers.rs, relayer/src/message_relayer/eth_to_gear/manual.rs, relayer/src/message_relayer/eth_to_gear/paid_token_transfers.rs, relayer/src/message_relayer/gear_to_eth/all_token_transfers.rs, relayer/src/message_relayer/gear_to_eth/manual.rs, relayer/src/message_relayer/gear_to_eth/paid_token_transfers.rs
- Changed code from using std channels to tokio channels
- No `block_on` and `spawn_blocking` used anymore (1), tokio tasks are used instead
(1) MessageSender cannot yet just use `tokio::task::spawn` because `send_recv` from Sails is not Send-able future. Investigate how to make it work
1) Make recovery in case of error graceful, do not simply restart the `run_inner()` in most cases
2) Add ability to resubscribe to GearApi and EthApi, necessary for 1)
@gshep
=> refactor(relayer): use proper async in relayer

relayer/src/message_relayer/common/gear/checkpoints_extractor.rs, relayer/src/message_relayer/eth_to_gear/all_token_transfers.rs, relayer/src/message_relayer/eth_to_gear/manual.rs, relayer/src/message_relayer/eth_to_gear/mod.rs, relayer/src/message_relayer/eth_to_gear/paid_token_transfers.rs, tests/src/relayer/eth_to_gear.rs
This removes requirement on waiting for checkpoint if you're trying to manually relay transaction. If tx checkpoint is already stored in light-client program we can just use it. 
@gshep
=> refactor(relayer): Send latest checkpoint from light-client program on startup

relayer/src/message_relayer/common/paid_messages_filter.rs
@gshep 
This prevents infinite looping in case one of channels closes unexpectedly:
=> fix(relayer): prevent PaidMessageFilter from looping infinitely

Cargo.lock, Cargo.toml, gear-rpc-client/src/lib.rs, relayer/Cargo.toml, relayer/src/cli/mod.rs, relayer/src/lib.rs, relayer/src/main.rs, relayer/src/message_relayer/common/ethereum/accumulator/mod.rs, relayer/src/message_relayer/common/ethereum/accumulator/utils.rs, relayer/src/message_relayer/common/ethereum/merkle_root_extractor.rs, relayer/src/message_relayer/common/gear/block_listener.rs, relayer/src/message_relayer/common/gear/checkpoints_extractor.rs, relayer/src/message_relayer/common/gear/message_data_extractor.rs, relayer/src/message_relayer/common/gear/message_paid_event_extractor.rs, relayer/src/message_relayer/common/gear/message_queued_event_extractor.rs, relayer/src/message_relayer/common/gear/mod.rs, relayer/src/message_relayer/common/mod.rs, relayer/src/message_relayer/common/paid_messages_filter.rs, relayer/src/message_relayer/eth_to_gear/api_provider.rs, relayer/src/message_relayer/gear_to_eth/all_token_transfers.rs, relayer/src/message_relayer/gear_to_eth/manual.rs, relayer/src/message_relayer/gear_to_eth/paid_token_transfers.rs, relayer/src/relay_merkle_roots.rs, relayer/src/server.rs
Resolves #519 
- new methods in gear-rpc-client & ApiProviderConnection
- refactor Accumulator, MerkleRootExtractor, MessageQueuedEventExtractor & PaidMessagesFilter
- refactor MerkleRoots collection
- move GearBlock & message_queued_event_of to the common module
- implement web server
- implement MessageDataExtractor. It gets all required data for the message requested to relay
- spawn fetch_merkle_roots task to get all required merkle roots
@gear-tech/dev
=> feat(relayer): Add POST-handler of a list to gear-eth

relayer/src/cli/mod.rs, relayer/src/common.rs, relayer/src/main.rs, relayer/src/merkle_roots/authority_set_sync.rs, relayer/src/merkle_roots/eras.rs, relayer/src/merkle_roots/mod.rs, relayer/src/merkle_roots/prover.rs, relayer/src/merkle_roots/storage.rs, relayer/src/merkle_roots/submitter.rs, relayer/src/message_relayer/common/gear/block_listener.rs, relayer/src/message_relayer/common/mod.rs, relayer/src/prover_interface.rs
Latest refactor for merkle-root relayer proven to be faulty esp. during era changes. This PR should improve the situation:
- Sealing of old eras now is only performed during startup without blocking authority set sync for new blocks
- Submitter task was changed to consider merkle-root submitted after 8 confirmations by default. Also added checks to not submit root if it is already on Ethereum.
- Merkle-root relayer was updated to use TxManaged like approach from eth-gear but for merkle-roots: now status of each merkle root we're relaying will be saved in storage. 
- Small refactor of block-listener to add `GearBlock::from_subxt_block` 
@gshep
=> refactor(relayer): Make merkle-root relayer more lazy

Cargo.lock
new version of `cc` has patch that allows it to work correctly with `clang-20`
this should also fix `rust-analyzer` on linux
=> fix: update `cc` to `1.2.34` to fix `rust-analyzer`

relayer/src/merkle_roots/mod.rs
After batching was introduced `self.roots.contains()` in `try_proof_merkle_proof` is not necessary anymore due to the fact that roots are checked appropriately when sending to prover. This check still could be triggered by roots in `WaitForAuthoritySetSync` state since they are not batched and still are stored in merkle_roots map.
=> fix(relayer): remove unecessary check for merkle-root generation
